title: 简历 - Java 开发工程师 - 张二狗

aboutme:
  name: 张二狗 / ErGouZhang
  sex: 男
  age: 25
  email: ergouzhang@gmail.com
  phone: 18866668888
  github: https://github.com/rgz
  city: 北京
  job: 算法工程师
  edu: 本科

update: 2020年05月24日